### ISSUE TITLE
InvalidLicenseMessage error while downloading a track

### ISSUE THREAD

**Issue by Lacanbonda** [devine-dl/devine#38]
**Describe the bug**
Hello,in v2.0.0 When i was trying to download with single workers am able to download only Video and Subtitle. Audio fails at last by saying  **"InvalidLicenseMessage: Could not parse license_message as a SignedMessage"** but the kid:key is same for both video and audio. while workers are more than one its fine in working both video and audio gets downloaded and mux.

**Expected behavior**
it should download video, audio and then sub with single workers.

**Screenshots**
while --workers 1
skipped audio: https://i.ibb.co/M5gjhvp/Screenshot-132.png
final result: https://i.ibb.co/42vYNQJ/Screenshot-133.png

**Additional context**
this happens only on cdm without Vault support while--workers 1. but when in vault its fine.

**Comment by rlaphoenix** [comment]
This is because for whatever reason, the license call for the audio track failed, while it was successful for the video track. This would be an error on your end duing the get_widevine_license() method. I would recommend giving a check on the output of any API calls and make sure it's not returning errors back to the DRM handler.

It works when you use vaults because when it was licensed for the Video call, it had keys for both the Video and Audio or they shared the same key. Without vaults it had nowhere to check if a KEY for the audio track's Key ID already existed, so it had to re-license.

**Comment by Lacanbonda** [comment]
yes your right token for license gets expired after 1st key i fixed.

one more doubt, while saving the content service tag takes from class when tired to set ALIASES it asks only for class type.

any possible to keep ALIASES as service tag which can be in short in filename.
