### ISSUE TITLE
download langauge subtitles

### ISSUE THREAD

**Issue by kkm** [devine-dl/devine#41]
I wish as title says.

**Comment by rlaphoenix** [comment]
Please elaborate, what you state here tells me absolutely nothing.

**Comment by kkm** [comment]
Sorry, model like NFripper or VT download specific subtitles and audio by language.

**Comment by kkm** [comment]
![image](https://user-images.githubusercontent.com/134290/224285504-d823b973-f21d-410a-90b2-44c1fd769cf4.png)

**Comment by rlaphoenix** [comment]
I'm not fully understanding your question. Are you asking for a way to choose which language to download? You can specify which language to download with `-l`, e.g., `-l fr` for French. You can specify multiple language, e.g., `-l fr,it` for French and Italian. The `-l` flag tells Devine to download that language for Videos, Audio, and Subtitles. If there's only English videos and it fails because you did `-l fr`, then you can request specifically the en video with `-l fr -vl en`.
