### ISSUE TITLE
Detect audio track of HLS stream if it's with the video track

### ISSUE THREAD

**Issue by nxmiru** [devine-dl/devine#66]
**Is your feature request related to a problem? Please describe.**
Some services have audio and video in the same track so devine can't detect audio. So, it's impossible to have a video with multiple audio with this configuration

**Describe the solution you'd like**
Detect and give the possibility to have multiple audio in this case

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/devine-dl/devine/assets/148786565/fd91bdee-34c5-48fa-ad64-18d506a0c324)

**Comment by rlaphoenix** [comment]
Hi, yes, 9292704B
________________________________
From: Namiru ***@***.***>
Sent: 23 October 2023 15:50
To: devine-dl/devine ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [devine-dl/devine] Detect audio track of HLS stream if it's with video track (Issue #66)


Is your feature request related to a problem? Please describe.
Some services have audio and video in the same track so devine can't detect audio. So, it's impossible to have a video with multiple audio with this configuration

Describe the solution you'd like
Detect and give the possibility to have multiple audio in this case

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Additional context
[image]<https://user-images.githubusercontent.com/148786565/277377925-fd91bdee-34c5-48fa-ad64-18d506a0c324.png>

**Comment by rlaphoenix** [comment]
Hi, that isn't possible. There's simply no way to derive such information if it's not listed in the M3U playlist split.

However, some services like BBC iPlayer secretly have separate manifests for video and audio on it's own that you can call separately and join together.

How they do that is the manifest URL would look like this: `-video_<id>=<bandwidth>-audio_<id>=<bandwidth>` and you can just strip off which one you don't want, then you have them as separate solo tracks in the manifest. The only problem is these split manifests are usually very bare of information and generally won't work with HLS class, you would need to make e.g. the `Audio` object yourself.

**Comment by rlaphoenix** [comment]
To be further clear on this, the reason the information cannot just be derived automatically is because the content simply isn't split/separate to do so. The video and audio data is transmuxed together, usually as a transport stream.

The only plausible way to download say the Japanese video and French audio, would be to download both (the jp video and audio and fr video and audio), and then discard the French video and Japanese audio.

In my opinion, this isn't a good solution and would be a rather painful thing to do, especially since the code flow can only recognize these types of manifest tracks as just a video track. Iternally it has no clue if it actually has audio or not. Therefore, implementing even such a wasteful download process would be tricky when it comes to the muxing job.

**Comment by nxmiru** [comment]
Indeed It actually works fine when I add audio tracks by hand, it's not really optimal because same video is downloaded twice (for video and audio) but I don't know if I can do better than this (I have to deal with duplicate video but it's ok)

**Comment by rlaphoenix** [comment]
> Indeed It actually works fine when I add audio tracks by hand, it's not really optimal because same video is downloaded twice (for video and audio) but I don't know if I can do better than this (I have to deal with duplicate video but it's ok)

Just to add in to this, for iPlayer you could remove something similar or such to `-video=1200000` from the URL, leaving behind `-audio=256000` or something, which results in JUST the audio being downloaded. This of course isn't always possible but it's something to try and really the only option when it comes to HLS TS playlists.
