### ISSUE TITLE
Downloading with aria2c 1.37.0 result in corrupted files

### ISSUE THREAD

**Issue by Shivelight** [devine-dl/devine#71]
**Describe the bug**
When using aria2c 1.37.0, I found that the segments temp directory contains `.aria2__temp` files, which devine will naively merge, resulting in a corrupted file.

Temporary fix is by using aria2c 1.36.0.

**To Reproduce**

1. Install aria2c 1.37.0
2. Run `devine dl`
3. If the stream is decrypted, you will see an error from shaka-packager, otherwise there's no error but the file is corrupted.

**Expected behavior**
Devine should not naively merge.

**Screenshots**
1.36.0
![image](https://github.com/devine-dl/devine/assets/20620780/1acb560a-af2a-4a68-9abe-2810c9a3d83f)

1.37.0
![image](https://github.com/devine-dl/devine/assets/20620780/91c0830a-5e85-42fd-855b-3593c1ad1d43)

**Additional context**
N/A

**Comment by rlaphoenix** [comment]
Ok, so multiple problems are going on with aria2c v1.37.0. I don't recommend using it, downgrade to v1.36.0 and use that instead in the meantime.

**Comment by rlaphoenix** [comment]
From aria2c's changelog (2007-09-02):

```
Now *.aria2 contorol file is first saved to *.aria2__temp and if it is successful, then renamed to *.aria2.
This prevents *.aria2 file from being truncated or corrupted when file system becomes out of space.
```

It seems something went wrong in 1.37.0 resulting in these files sometimes not being renamed back to `.aria2` and then being left there for good. The fix for devine would be to simply detect `.aria2__temp` and delete them once all segments finish downloading. My only worry here is the root cause for why it has failed to rename. Did the download actually complete without error? According to aria2c's RPC, no errors occurred. There's no way to add support for Aria2(c) 1.37.0 without this sort of change as the files to seem to download correctly regardless of the file not being renamed and then deleted.

I should also note that on your system ALL segments failed to rename and got stuck forever, but on mine, only 1 segment near the very start got hit with it. The 4th segment file.

**Comment by rlaphoenix** [comment]
Any further info should be disclosed upstream unless it's specifically to do with devine: https://github.com/aria2/aria2/issues/2189
