### ISSUE TITLE
Add possibility to add attachements to mkv file

### ISSUE THREAD

**Issue by nxmiru** [devine-dl/devine#82]
**Is your feature request related to a problem? Please describe.**
If an ASS subtitle use a font not recognized (because it is not present anywhere), it fallback to a alternative font in most case. But it can break subtitles in some case like when it have typesetting

| With font | Without font |
| -------- | ------- |
| ![mpv-shot0003](https://github.com/devine-dl/devine/assets/148786565/7a8ef9f0-6b9f-46e6-9174-1892763a1b03) | ![mpv-shot0005](https://github.com/devine-dl/devine/assets/148786565/13d993bd-c87d-441e-b632-f9ca84f869e9) |

**Describe the solution you'd like**
A way to add attachments to the final mkv file

**Describe alternatives you've considered**
As for now, I just edited `mux` method with this:
![image](https://github.com/devine-dl/devine/assets/148786565/6dd9d8fc-612a-44cd-b586-7ad85386674d)

**Comment by rlaphoenix** [comment]
Hi,

I am working on this now with CR, do you have any recommendations on how to handle what fonts to include? My strategy right now is to fetch font names from every ASS subs while still within get_tracks(), and then include that font family of subs by using the Subs from CR's CDN API.

![image](https://github.com/devine-dl/devine/assets/17136956/fe0aee7a-0539-422e-9727-89a79045efeb)

As you can see for one Episode with 4 Subtitles, 5 total font families were used throughout the subs, and 17 total font files are used to make up the font families. This seems excessive and I'm just looking for recommendations on what people in Anime scene usually do regarding this. I am grabbing fonts for all subs, because after all if you only do it for say the English subs, then it being a multi-sub release is a bit pointless.

This is what I'm doing at the tail end of get_tracks() for CR:

![image](https://github.com/devine-dl/devine/assets/17136956/1fa88ade-bac4-4c76-b7da-a448969c1980)

The only problem here is it does it for *every* sub, not every CHOSEN sub, but every sub. Since filtering of subs are done in the dl command's code, it's a bit of a problem to know what subs will or wont be selected for download. So atm its just grabbing font names from all ASS subs.

**Comment by rlaphoenix** [comment]
As of https://github.com/devine-dl/devine/commit/b2161d0476bd545abb54bf87abd4799edd8eefb8 the bones for adding font attachments is possible, but the solution of doing it from the Service class seems over complicated. I will instead try to implement it within the dl command code to automatically run after downloading ASS subs (and maybe VTT?). Fonts could perhaps be placed in a new configurable directory, and defaulting to the same kind of location as the services folder.

**Comment by rlaphoenix** [comment]
Ok so with the above commit it now automatically tries attaching fonts used within SSAv4 subs (listed as ASS in the tracks list) once all tracks are downloaded, just in time to be muxed with mkvmerge. You place the fonts in /devine/fonts (next to core/services folder). You can move this fonts folder with the `directories` option in the config.

The fonts folder must have font files (ttf/otf) in sub-folders with the sub-folders being the name of the font family (the name listed in the Subtitle). E.g., if the Subtitle says "Trebuchet MS" then make a `/devine/fonts/Trebuchet MS` folder and for CR it would usually need `trebuc.ttf`, `trebucbd.ttf`, `trebucbi.ttf`, and `trebucit.tff` within that folder.

Finally, on Windows if its looking for a common font say "Arial" that is installed on your system, it tries to find it and include it. However, the /devine/fonts folder is prioritized over, and the two locations are NOT merged. So even if one font variant say bold is missing from /devine/fonts/Arial, it will not include the bold variant from the System OS. You would need to include it in the folder.

I am not up-to-date on what the anime scene does regarding fonts and what ones to attach. If you have any ideas on improving this system, let me know.
